name: Minify, Obfuscate, and Deploy JS

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  minify_obfuscate_deploy:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu runner

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Set the Node.js version here

      - name: Install dependencies
        run: |
          npm install terser javascript-obfuscator --save-dev

      - name: Minify JavaScript
        run: |
          npx terser src/*.js --compress --mangle --output dist/minified.js  # Minify JS from src to dist/minified.js

      - name: Obfuscate JavaScript
        run: |
          npx javascript-obfuscator dist/minified.js --output dist/obfuscated.js  # Obfuscate the minified JS

      - name: Set up Git for deployment
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Deploy to GitHub Pages
        run: |
          git clone --depth 1 https://github.com/${{ github.repository }} gh-pages  # Clone the repository
          cd gh-pages
          cp ../dist/obfuscated.js .  # Copy the obfuscated JS to the root of gh-pages folder
          git add .
          git commit -m "Deploy obfuscated JS to GitHub Pages"
          git push origin main  # Push to the `main` branch (root folder of GitHub Pages)

